#!/usr/bin/env bash
# This script is the agent that listen for the input of a user to lunch the dependencies
# scripts that make the agent work.
#
# Author: Decarnelle Samuel

# === HASHRELAY AGENT ===
# A simple dispatcher CLI agent

# Ensure we are root
if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  echo "HashRelay must be run as root (use sudo)." >&2
  exit 1
fi

ADD=false
REMOVE=false

# usage(): print help text:
usage() {
  cat <<'USAGE'
  HASHRELAY
  Options:
    --config                  Change the configuration in your local machine
    --add                     Add a file/directory to the backups list
    --remove                  Remove a file/directory the the backups list
    -h|--help                 This help
  Environement:
    This agent work is used to make backups in your local machine and send them 
    automatically onto your configured server.
  Behavior:
    You must call the agent with flag to interact with him.
USAGE
}

# Parse CLI arguments in a loop until all are consumed
while [[ $# -gt 0 ]]; do
  case "$1" in
  --config)
    exec sudo bash /usr/local/bin/HashRelay/hashrelay-client/hashrelay-client.sh # Lunch the config script
    shift
    ;;
  --add)
    ADD=true # To add to the backup list
    shift
    ;;
  --remove)
    REMOVE=true # To remove from the backup list
    shift
    ;;
  -h | --help)
    usage
    exit 0
    ;;
  *)
    echo "[!] Unknow arg: $1"
    usage
    exit 1
    ;;
  esac
done

# Set the add function if the user called the agent with add flag
add_file() {
  local input="$1"

  # If input is absolute path
  if [[ "$input" = /* ]]; then
    filepath="$input"
  else
    # Relative file → resolve to current directory path
    filepath="$(pwd)/$input"
  fi

  # Check if the file exists
  if [[ -e "$filepath" ]]; then # True if the path exists as anything (file, directory, symlink, socket, device, etc) -d for directory -f for file
    echo "hashrelay has added $filepath"
  else
    echo "hashrelay cannot add $input, verify your file name or path"
    exit 1
  fi
}

if [[ "$ADD" == true ]]; then
  add_file

  case "$1" in
  --add)
    if [[ -z "$2" ]]; then
      echo "[!] Missing argument: you must provide a file name."
      exit 1
    fi
    add_file "$2"
    ;;

  *)
    echo "Unknown command: $1"
    ;;
  esac
fi
